// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXS3wJ0g3hiCWiHheHDYCAsEd_ave4fQ',
    appId: '1:180850621786:android:460d9fe6e24c427bc14763',
    messagingSenderId: '180850621786',
    projectId: 'fir-otp-auth-app',
    storageBucket: 'fir-otp-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8seqOJ3hBJV60l8dVGnstRf72q_z2YM',
    appId: '1:180850621786:ios:8269ee7039372231c14763',
    messagingSenderId: '180850621786',
    projectId: 'fir-otp-auth-app',
    storageBucket: 'fir-otp-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOtpLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8seqOJ3hBJV60l8dVGnstRf72q_z2YM',
    appId: '1:180850621786:ios:8269ee7039372231c14763',
    messagingSenderId: '180850621786',
    projectId: 'fir-otp-auth-app',
    storageBucket: 'fir-otp-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOtpLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrvarQWNxrMgYzOcJXziNIeo7xe1eWcCI',
    appId: '1:180850621786:web:b0f838716b86a402c14763',
    messagingSenderId: '180850621786',
    projectId: 'fir-otp-auth-app',
    authDomain: 'fir-otp-auth-app.firebaseapp.com',
    storageBucket: 'fir-otp-auth-app.firebasestorage.app',
    measurementId: 'G-1X65V61QVY',
  );
}
